nome = str(input("Digite seu nome completo:"))
m = nome.upper()
min = nome.lower()
tamanho = len(nome) - nome.count(" ")
separado = nome.split()
print ("Seu nome em letras maiúsculas é:".format(m))
print ("Seu nome em letras minúsculas é:".format(min))
print ("Seu nome tem {} letras".format(tamanho))
print ("Seu primeiro nome é {}".format(separado[0]))